apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc02
  annotations:
    volume.beta.kubernetes.io/storage-class: fast 
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteOnce

